# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RE58C2/setup-makefiles.sh

$(warning Including RE58C2-vendor.mk)


# Enable Android.bp processing for this vendor directory
SOONG_CONFIG_NAMESPACES += realme_RE58C2_vendor
SOONG_CONFIG_realme_RE58C2_vendor += target_uses_vendor_bp
SOONG_CONFIG_realme_RE58C2_vendor_target_uses_vendor_bp := true
 

PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/etc/audio_effects.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/audio_effects.conf \
    vendor/realme/RE58C2/proprietary/etc/temperature_profile/sys_high_temperature.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/temperature_profile/sys_high_temperature.xml \
    vendor/realme/RE58C2/proprietary/lib/libois_algorithm_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libois_algorithm_jni.so \
    vendor/realme/RE58C2/proprietary/lib/libremotedisplay.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libremotedisplay.so \
    vendor/realme/RE58C2/proprietary/lib/libstagefright_surface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_surface.so \
    vendor/realme/RE58C2/proprietary/lib64/libois_algorithm_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libois_algorithm_jni.so \
    vendor/realme/RE58C2/proprietary/lib64/libremotedisplay.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libremotedisplay.so \
    vendor/realme/RE58C2/proprietary/lib64/libstagefright_surface.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libstagefright_surface.so

# ODM audio configuration files
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.xml,vendor/realme/RE58C2/proprietary/odm/etc/audio,$(TARGET_COPY_OUT_ODM)/etc/audio) \
    $(call find-copy-subdir-files,*.xml,vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd,$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd) \
    $(call find-copy-subdir-files,*.xml,vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/version1,$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/version1)

# ODM build properties
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.prop,vendor/realme/RE58C2/proprietary/odm/etc,$(TARGET_COPY_OUT_ODM)/etc)

# ODM camera configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/fwk_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/fwk_config.json

# ODM camera filters and LUTs (bulk copy)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.,vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool,$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool)

# ODM init scripts
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/init/init.jiiov.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.jiiov.rc

# ODM ISP pipeline configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/isppipeline/Pipeline_Linkage.json:$(TARGET_COPY_OUT_ODM)/etc/isppipeline/Pipeline_Linkage.json \
    vendor/realme/RE58C2/proprietary/odm/etc/isppipeline/props.xml:$(TARGET_COPY_OUT_ODM)/etc/isppipeline/props.xml

# ODM NFC configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/libnfc_accesscard_config.conf:$(TARGET_COPY_OUT_ODM)/etc/libnfc_accesscard_config.conf \
    vendor/realme/RE58C2/proprietary/odm/etc/libnfc_default_config.conf:$(TARGET_COPY_OUT_ODM)/etc/libnfc_default_config.conf

# ODM LWP topology files (bulk copy)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.json,vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology,$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology)

# ODM media codecs
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/media_codecs_c2_secure.xml:$(TARGET_COPY_OUT_ODM)/etc/media_codecs_c2_secure.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/media_codecs_performance_c2_secure.xml:$(TARGET_COPY_OUT_ODM)/etc/media_codecs_performance_c2_secure.xml

# ODM OTP data
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.txt,vendor/realme/RE58C2/proprietary/odm/etc/otpdata,$(TARGET_COPY_OUT_ODM)/etc/otpdata)

# ODM sensor configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/sensor_config.xml:$(TARGET_COPY_OUT_ODM)/etc/sensor_config.xml

# ODM UniPNP configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/unipnp/UniFeature.xml:$(TARGET_COPY_OUT_ODM)/etc/unipnp/UniFeature.xml

# ODM WiFi configuration
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.ini,vendor/realme/RE58C2/proprietary/odm/etc,$(TARGET_COPY_OUT_ODM)/etc)

# ODM zoom configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/zoom_config.json:$(TARGET_COPY_OUT_ODM)/etc/zoom_config.json

# ODM libraries (both 32-bit and 64-bit)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.so,vendor/realme/RE58C2/proprietary/odm/lib,$(TARGET_COPY_OUT_ODM)/lib) \
    $(call find-copy-subdir-files,*.so,vendor/realme/RE58C2/proprietary/odm/lib64,$(TARGET_COPY_OUT_ODM)/lib64)

# System_ext files
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/system_ext/etc/camera/default_cnr3_param.txt:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/default_cnr3_param.txt \
    vendor/realme/RE58C2/proprietary/system_ext/etc/camera/default_ynr_param.txt:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/default_ynr_param.txt \
    vendor/realme/RE58C2/proprietary/system_ext/etc/init/dataLogDaemon.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dataLogDaemon.rc \
    vendor/realme/RE58C2/proprietary/system_ext/etc/init/data_rps.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/data_rps.rc

# =============================================
# Vendor DLKM Modules
# =============================================

# Kernel modules (bulk copy)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.ko,vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules,$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules)

# Module metadata files
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.alias:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.alias \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.dep:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.dep \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.softdep:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.softdep

# Module loading configs
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.load:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.load.cali:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load.cali \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.load.charger:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load.charger

# Critical hardware modules
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/mali_kbase.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/mali_kbase.ko \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/sprd_wlan_combo.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/sprd_wlan_combo.ko \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/sprd_thermal.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/sprd_thermal.ko

# Init configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/init.insmod.cfg:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/init.insmod.cfg

# Build properties
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/etc/build.prop:$(TARGET_COPY_OUT_VENDOR_DLKM)/etc/build.prop

# SELinux contexts
#PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/etc/selinux/vendor_file_contexts:$(TARGET_COPY_OUT_VENDOR_DLKM)/etc/selinux/vendor_file_contexts

# =============================================
# Complete Stock Vendor SELinux Stack
# =============================================

# Vendor SELinux Policy
#PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_file_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_file_contexts \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_hwservice_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_hwservice_contexts \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_mac_permissions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_mac_permissions.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_property_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_property_contexts \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_seapp_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_seapp_contexts \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_sepolicy.cil:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_sepolicy.cil \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_service_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_service_contexts \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vndservice_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vndservice_contexts

# Platform policy version (important!)
#PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/plat_sepolicy_vers.txt:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/plat_sepolicy_vers.txt
    
     
# ========================
# Essential System Components
# ========================
PRODUCT_PACKAGES += \
    charger \
    charger_res_images \
    watchdogd