# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RE58C2/setup-makefiles.sh

$(warning Including RE58C2-vendor.mk)


# Enable Android.bp processing for this vendor directory
SOONG_CONFIG_NAMESPACES += realme_RE58C2_vendor
SOONG_CONFIG_realme_RE58C2_vendor += target_uses_vendor_bp
SOONG_CONFIG_realme_RE58C2_vendor_target_uses_vendor_bp := true
 

PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/etc/audio_effects.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/audio_effects.conf \
    vendor/realme/RE58C2/proprietary/etc/temperature_profile/sys_high_temperature.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/temperature_profile/sys_high_temperature.xml \
    vendor/realme/RE58C2/proprietary/lib/libois_algorithm_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libois_algorithm_jni.so \
    vendor/realme/RE58C2/proprietary/lib/libremotedisplay.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libremotedisplay.so \
    vendor/realme/RE58C2/proprietary/lib/libstagefright_surface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_surface.so \
    vendor/realme/RE58C2/proprietary/lib64/libois_algorithm_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libois_algorithm_jni.so \
    vendor/realme/RE58C2/proprietary/lib64/libremotedisplay.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libremotedisplay.so \
    vendor/realme/RE58C2/proprietary/lib64/libstagefright_surface.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libstagefright_surface.so

# ODM audio configuration files
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.xml,vendor/realme/RE58C2/proprietary/odm/etc/audio,$(TARGET_COPY_OUT_ODM)/etc/audio) \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/etc/audio_params,$(TARGET_COPY_OUT_ODM)/etc/audio_params)

# ODM build properties
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.prop,vendor/realme/RE58C2/proprietary/odm/etc,$(TARGET_COPY_OUT_ODM)/etc)

# ODM camera configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/fwk_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/fwk_config.json

# ODM camera filters and LUTs (fixed bulk copy)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool,$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool)

# ODM binaries
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/bin/CamDevSim:$(TARGET_COPY_OUT_ODM)/bin/CamDevSim \
    vendor/realme/RE58C2/proprietary/odm/bin/fm_tools:$(TARGET_COPY_OUT_ODM)/bin/fm_tools

# ODM firmware
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/firmware,$(TARGET_COPY_OUT_ODM)/firmware)

# ODM init scripts
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/init/init.jiiov.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.jiiov.rc

# ODM ISP pipeline configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/isppipeline/Pipeline_Linkage.json:$(TARGET_COPY_OUT_ODM)/etc/isppipeline/Pipeline_Linkage.json \
    vendor/realme/RE58C2/proprietary/odm/etc/isppipeline/props.xml:$(TARGET_COPY_OUT_ODM)/etc/isppipeline/props.xml

# ODM NFC configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/libnfc_accesscard_config.conf:$(TARGET_COPY_OUT_ODM)/etc/libnfc_accesscard_config.conf \
    vendor/realme/RE58C2/proprietary/odm/etc/libnfc_default_config.conf:$(TARGET_COPY_OUT_ODM)/etc/libnfc_default_config.conf

# ODM LWP topology files (bulk copy)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology,$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology)

# ODM media codecs
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/media_codecs_c2_secure.xml:$(TARGET_COPY_OUT_ODM)/etc/media_codecs_c2_secure.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/media_codecs_performance_c2_secure.xml:$(TARGET_COPY_OUT_ODM)/etc/media_codecs_performance_c2_secure.xml

# ODM OTP data (fixed to include all files)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/etc/otpdata,$(TARGET_COPY_OUT_ODM)/etc/otpdata)

# ODM sensor configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/sensor_config.xml:$(TARGET_COPY_OUT_ODM)/etc/sensor_config.xml

# ODM VINTF manifests
#PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/etc/vintf,$(TARGET_COPY_OUT_ODM)/etc/vintf)

# ODM UniPNP configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/unipnp/UniFeature.xml:$(TARGET_COPY_OUT_ODM)/etc/unipnp/UniFeature.xml

# ODM WiFi configuration
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.ini,vendor/realme/RE58C2/proprietary/odm/etc,$(TARGET_COPY_OUT_ODM)/etc)

# ODM zoom configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/zoom_config.json:$(TARGET_COPY_OUT_ODM)/etc/zoom_config.json

# ODM logo files
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/logo,$(TARGET_COPY_OUT_ODM)/logo)

# ODM libraries (both 32-bit and 64-bit)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.so,vendor/realme/RE58C2/proprietary/odm/lib,$(TARGET_COPY_OUT_ODM)/lib) \
    $(call find-copy-subdir-files,*.so,vendor/realme/RE58C2/proprietary/odm/lib64,$(TARGET_COPY_OUT_ODM)/lib64)

# ODM SELinux policies and precompiled policy
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/precompiled_sepolicy:$(TARGET_COPY_OUT_ODM)/etc/selinux/precompiled_sepolicy \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/odm_file_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_file_contexts \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/odm_sepolicy.cil:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_sepolicy.cil \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/odm_mac_permissions.xml:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_mac_permissions.xml

    # vendor/realme/RE58C2/proprietary/odm/etc/selinux/precompiled_sepolicy.plat_sepolicy_and_mapping.sha256:$(TARGET_COPY_OUT_ODM)/etc/selinux/precompiled_sepolicy.plat_sepolicy_and_mapping.sha256 \
    # vendor/realme/RE58C2/proprietary/odm/etc/selinux/precompiled_sepolicy.system_ext_sepolicy_and_mapping.sha256:$(TARGET_COPY_OUT_ODM)/etc/selinux/precompiled_sepolicy.system_ext_sepolicy_and_mapping.sha256 \



# Optional ODM context files (empty files, but include for completeness)
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/odm_hwservice_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_hwservice_contexts \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/odm_property_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_property_contexts \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/odm_seapp_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_seapp_contexts


# System_ext files
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/system_ext/etc/camera/default_cnr3_param.txt:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/default_cnr3_param.txt \
    vendor/realme/RE58C2/proprietary/system_ext/etc/camera/default_ynr_param.txt:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/default_ynr_param.txt \
    vendor/realme/RE58C2/proprietary/system_ext/etc/init/dataLogDaemon.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dataLogDaemon.rc \
    vendor/realme/RE58C2/proprietary/system_ext/etc/init/data_rps.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/data_rps.rc

# =============================================
# Vendor DLKM Modules
# =============================================

# Kernel modules (bulk copy)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.ko,vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules,$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules)

# Module metadata files
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.alias:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.alias \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.dep:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.dep \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.softdep:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.softdep

# Module loading configs
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.load:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.load.cali:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load.cali \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.load.charger:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load.charger

# Critical hardware modules
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/mali_kbase.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/mali_kbase.ko \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/sprd_wlan_combo.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/sprd_wlan_combo.ko \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/sprd_thermal.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/sprd_thermal.ko

# Init configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/init.insmod.cfg:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/init.insmod.cfg

# Build properties
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/etc/build.prop:$(TARGET_COPY_OUT_VENDOR_DLKM)/etc/build.prop

# Copy all fstab variants from vendor/realme/RE58C2/proprietary/vendor/etc
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.cali:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.cali \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.charge_mode:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.charge_mode \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.enableswap:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.enableswap \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.module:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.module \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.RE58C2:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.RE58C2 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.RMX3624:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.RMX3624 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_1h10:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_1h10 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_1h10_go:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_1h10_go \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_4h10:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_4h10 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_4h10_go:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_4h10_go \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_6h10:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_6h10 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_7h10:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_7h10 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_haps:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_haps \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_hulk:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_hulk \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_nico:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_nico \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_zebu:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_zebu



#----------------------------------------------------------------------
# Copy all fstab files for hardware-specific mounting
#----------------------------------------------------------------------
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.cali:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.cali \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.charge_mode:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.charge_mode \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.enableswap:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.enableswap \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.module:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.module \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.RE58C2:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.RE58C2 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.RMX3624:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.RMX3624 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_1h10:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_1h10 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_1h10_go:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_1h10_go \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_4h10:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_4h10 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_4h10_go:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_4h10_go \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_6h10:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_6h10 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_7h10:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_7h10 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_haps:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_haps \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_hulk:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_hulk \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_nico:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_nico \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_zebu:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_zebu



#PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/vendor/etc/init,$(TARGET_COPY_OUT_VENDOR)/etc/init)

# RC Files product_copy_files
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.audio.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.audio.service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service.unisoc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service.unisoc.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.camera.provider@2.4-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.camera.provider@2.4-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.cas@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.cas@1.2-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.graphics.composer@2.4-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.composer@2.4-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.drm-service.clearkey.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.clearkey.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.drm-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.widevine.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service.trusty.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service.trusty.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.health-service.example.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.health-service.example.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.media.c2@1.1-unisoc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.1-unisoc-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.media.omx@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.omx@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-armnn-gpu.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-armnn-gpu.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.nfc@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.nfc@1.2-service.rc \
    vendor/realme/RE58C2/proprietary/system_ext/etc/init/dataLogDaemon.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dataLogDaemon.rc \
    vendor/realme/RE58C2/proprietary/system_ext/etc/init/data_rps.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/data_rps.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/unisoc.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/unisoc.rild.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.security.keymint@2.0-unisoc.service.trusty.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint@2.0-unisoc.service.trusty.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.sensors-service-multihal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors-service-multihal.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.usb-service.example.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb-service.example.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.wifi.supplicant-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi.supplicant-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.wifi@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/odm/etc/init/init.jiiov.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.jiiov.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/ai_engine-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ai_engine-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/autotest.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/autotest.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/boringssl_self_test.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/boringssl_self_test.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/charge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/charge.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/charged.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/charged.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/connmgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/connmgr.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/cp_diskserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cp_diskserver.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/cplog_svc-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cplog_svc-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/dcxsrv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dcxsrv.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/engpc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/engpc.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/enhance-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/enhance-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/face-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/face-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/hdcp-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hdcp-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/hostapd.android.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hostapd.android.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/init.guid.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.guid.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/init.md.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.md.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/init.ums9230_hulk_Natv.nfc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.ums9230_hulk_Natv.nfc.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/lights.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lights.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/memtrack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/memtrack.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/modem_control.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/modem_control.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/network-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/network-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/phasecheckserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/phasecheckserver.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/power.stats-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/power.stats-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/rebootescrow-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rebootescrow-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/refnotify.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/refnotify.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/remosaic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/remosaic.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/rpmbserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rpmbserver.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/slogmodem_vendor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/slogmodem_vendor.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/soter-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/soter-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/srtd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/srtd.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/storageproxyd_android.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/storageproxyd_android.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/systemDebuggerd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/systemDebuggerd.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/tee_rpc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee_rpc.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/thermald.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/thermald.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/trusty-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trusty-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/tsupplicant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tsupplicant.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/tui-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tui-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor-fingerprintmmi-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor-fingerprintmmi-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor-oemlock-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor-oemlock-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor-power-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor-power-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.log-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.log-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.oppo.engnative.engineer@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.oppo.engnative.engineer@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.boot@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.boot@1.2-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.broadcastradio@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.broadcastradio@2.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.commondcs@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.commondcs@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.connmgr@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.connmgr@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.gnss@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.gnss@2.2-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.network@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.network@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.performance@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.performance@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.thermal@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.thermal@2.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.wcn@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.wcn@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor_engineermode.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor_engineermode.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vibrator.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vibrator.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vndservicemanager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vndservicemanager.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vowifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vowifi.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/wcn.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wcn.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/wcn_chr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wcn_chr.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/yloglite.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/yloglite.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/ueventd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/ueventd.rc


# ===========================
# MISSING VENDOR BINARIES - CORRECT PATHS
# ===========================

# Core vendor binaries
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/bin/charged:$(TARGET_COPY_OUT_VENDOR)/bin/charged \
    vendor/realme/RE58C2/proprietary/vendor/bin/uniber:$(TARGET_COPY_OUT_VENDOR)/bin/uniber \
    vendor/realme/RE58C2/proprietary/vendor/bin/phasecheckserver:$(TARGET_COPY_OUT_VENDOR)/bin/phasecheckserver \
    vendor/realme/RE58C2/proprietary/vendor/bin/refnotify:$(TARGET_COPY_OUT_VENDOR)/bin/refnotify \
    vendor/realme/RE58C2/proprietary/vendor/bin/slogmodem_vendor:$(TARGET_COPY_OUT_VENDOR)/bin/slogmodem_vendor \
    vendor/realme/RE58C2/proprietary/vendor/bin/srtd:$(TARGET_COPY_OUT_VENDOR)/bin/srtd

# HAL services
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.gnss@2.2-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.gnss@2.2-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.camera.provider@2.4-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.camera.provider@2.4-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.drm-service.clearkey:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm-service.clearkey \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.gatekeeper@1.0-service.trusty:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper@1.0-service.trusty \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.nfc@1.2-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.nfc@1.2-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.wifi@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.wifi@1.0-service

# Sprd HAL services
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.cplog_svc-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.cplog_svc-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.enhance-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.enhance-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.hdcp-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.hdcp-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.lights-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.lights-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.memtrack-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.memtrack-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.network-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.network-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.oemlock-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.oemlock-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.log-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.log-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.broadcastradio@2.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.broadcastradio@2.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.commondcs@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.commondcs@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.network@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.network@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.performance@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.performance@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.vibrator-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.vibrator-service

# Additional services
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.rebootescrow-service.default:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.rebootescrow-service.default \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.oppo.engnative.engineer@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.oppo.engnative.engineer@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.media.c2@1.1-unisoc-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.media.c2@1.1-unisoc-service

# Vendor SELinux policies (complete stock versions)
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_sepolicy.cil:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_sepolicy.cil \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_file_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_file_contexts \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_property_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_property_contexts \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_service_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_service_contexts \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_hwservice_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_hwservice_contexts \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vndservice_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vndservice_contexts \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_mac_permissions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_mac_permissions.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/selinux/vendor_seapp_contexts:$(TARGET_COPY_OUT_VENDOR)/etc/selinux/vendor_seapp_contexts


PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/lib,$(TARGET_COPY_OUT_VENDOR)/lib) \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/lib64,$(TARGET_COPY_OUT_VENDOR)/lib64)


# Essential System Components
# ========================
PRODUCT_PACKAGES += \
    charger \
    charger_res_images \
    watchdogd
