# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RE58C2/setup-makefiles.sh

$(warning Including RE58C2-vendor.mk)


# Enable Android.bp processing for this vendor directory
SOONG_CONFIG_NAMESPACES += realme_RE58C2_vendor
SOONG_CONFIG_realme_RE58C2_vendor += target_uses_vendor_bp
SOONG_CONFIG_realme_RE58C2_vendor_target_uses_vendor_bp := true
 

PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/etc/audio_effects.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/audio_effects.conf \
    vendor/realme/RE58C2/proprietary/etc/temperature_profile/sys_high_temperature.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/temperature_profile/sys_high_temperature.xml \
    vendor/realme/RE58C2/proprietary/lib/libois_algorithm_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libois_algorithm_jni.so \
    vendor/realme/RE58C2/proprietary/lib/libremotedisplay.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libremotedisplay.so \
    vendor/realme/RE58C2/proprietary/lib/libstagefright_surface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_surface.so \
    vendor/realme/RE58C2/proprietary/lib64/libois_algorithm_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libois_algorithm_jni.so \
    vendor/realme/RE58C2/proprietary/lib64/libremotedisplay.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libremotedisplay.so \
    vendor/realme/RE58C2/proprietary/lib64/libstagefright_surface.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libstagefright_surface.so

# ODM audio configuration files
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.xml,vendor/realme/RE58C2/proprietary/odm/etc/audio,$(TARGET_COPY_OUT_ODM)/etc/audio) \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/etc/audio_params,$(TARGET_COPY_OUT_ODM)/etc/audio_params)

# ODM build properties
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.prop,vendor/realme/RE58C2/proprietary/odm/etc,$(TARGET_COPY_OUT_ODM)/etc)

# ODM camera configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/fwk_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/fwk_config.json

# ODM camera filters and LUTs (fixed bulk copy)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool,$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool)

# ODM binaries
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/bin/CamDevSim:$(TARGET_COPY_OUT_ODM)/bin/CamDevSim \
    vendor/realme/RE58C2/proprietary/odm/bin/fm_tools:$(TARGET_COPY_OUT_ODM)/bin/fm_tools

# ODM firmware
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/firmware,$(TARGET_COPY_OUT_ODM)/firmware)

# ODM init scripts
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/init/init.jiiov.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.jiiov.rc

# ODM ISP pipeline configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/isppipeline/Pipeline_Linkage.json:$(TARGET_COPY_OUT_ODM)/etc/isppipeline/Pipeline_Linkage.json \
    vendor/realme/RE58C2/proprietary/odm/etc/isppipeline/props.xml:$(TARGET_COPY_OUT_ODM)/etc/isppipeline/props.xml

# ODM NFC configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/libnfc_accesscard_config.conf:$(TARGET_COPY_OUT_ODM)/etc/libnfc_accesscard_config.conf \
    vendor/realme/RE58C2/proprietary/odm/etc/libnfc_default_config.conf:$(TARGET_COPY_OUT_ODM)/etc/libnfc_default_config.conf

# ODM LWP topology files (bulk copy)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology,$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology)

# ODM media codecs
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/media_codecs_c2_secure.xml:$(TARGET_COPY_OUT_ODM)/etc/media_codecs_c2_secure.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/media_codecs_performance_c2_secure.xml:$(TARGET_COPY_OUT_ODM)/etc/media_codecs_performance_c2_secure.xml

# ODM OTP data (fixed to include all files)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/etc/otpdata,$(TARGET_COPY_OUT_ODM)/etc/otpdata)

# ODM sensor configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/sensor_config.xml:$(TARGET_COPY_OUT_ODM)/etc/sensor_config.xml

# ODM VINTF manifests
#PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/etc/vintf,$(TARGET_COPY_OUT_ODM)/etc/vintf)

# ODM UniPNP configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/unipnp/UniFeature.xml:$(TARGET_COPY_OUT_ODM)/etc/unipnp/UniFeature.xml

# ODM WiFi configuration
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.ini,vendor/realme/RE58C2/proprietary/odm/etc,$(TARGET_COPY_OUT_ODM)/etc)

# ODM zoom configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/zoom_config.json:$(TARGET_COPY_OUT_ODM)/etc/zoom_config.json

# ODM logo files
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/odm/logo,$(TARGET_COPY_OUT_ODM)/logo)

# ODM libraries (both 32-bit and 64-bit)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.so,vendor/realme/RE58C2/proprietary/odm/lib,$(TARGET_COPY_OUT_ODM)/lib) \
    $(call find-copy-subdir-files,*.so,vendor/realme/RE58C2/proprietary/odm/lib64,$(TARGET_COPY_OUT_ODM)/lib64)

# ODM SELinux policies and precompiled policy
# PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/precompiled_sepolicy:$(TARGET_COPY_OUT_ODM)/etc/selinux/precompiled_sepolicy \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/odm_file_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_file_contexts \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/odm_sepolicy.cil:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_sepolicy.cil \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/odm_mac_permissions.xml:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_mac_permissions.xml\
    # vendor/realme/RE58C2/proprietary/odm/etc/selinux/precompiled_sepolicy.plat_sepolicy_and_mapping.sha256:$(TARGET_COPY_OUT_ODM)/etc/selinux/precompiled_sepolicy.plat_sepolicy_and_mapping.sha256 \
    # vendor/realme/RE58C2/proprietary/odm/etc/selinux/precompiled_sepolicy.system_ext_sepolicy_and_mapping.sha256:$(TARGET_COPY_OUT_ODM)/etc/selinux/precompiled_sepolicy.system_ext_sepolicy_and_mapping.sha256 \



# Optional ODM context files (empty files, but include for completeness)
# PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/odm_hwservice_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_hwservice_contexts \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/odm_property_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_property_contexts \
    vendor/realme/RE58C2/proprietary/odm/etc/selinux/odm_seapp_contexts:$(TARGET_COPY_OUT_ODM)/etc/selinux/odm_seapp_contexts



# =============================================
# Vendor DLKM Modules
# =============================================

# Kernel modules (bulk copy)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.ko,vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules,$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules)

# Module metadata files
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.alias:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.alias \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.dep:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.dep \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.softdep:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.softdep

# Module loading configs
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.load:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.load.cali:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load.cali \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.load.charger:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load.charger

# Critical hardware modules
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/mali_kbase.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/mali_kbase.ko \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/sprd_wlan_combo.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/sprd_wlan_combo.ko \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/sprd_thermal.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/sprd_thermal.ko

# Init configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/init.insmod.cfg:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/init.insmod.cfg

# Build properties
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/etc/build.prop:$(TARGET_COPY_OUT_VENDOR_DLKM)/etc/build.prop


# RC Files product_copy_files
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.audio.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.audio.service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service.unisoc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service.unisoc.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.camera.provider@2.4-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.camera.provider@2.4-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.cas@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.cas@1.2-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.graphics.composer@2.4-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.composer@2.4-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.drm-service.clearkey.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.clearkey.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.drm-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.widevine.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service.trusty.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service.trusty.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.health-service.example.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.health-service.example.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.media.c2@1.1-unisoc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.1-unisoc-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.media.omx@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.omx@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-armnn-gpu.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-armnn-gpu.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.nfc@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.nfc@1.2-service.rc \
    vendor/realme/RE58C2/proprietary/system_ext/etc/init/dataLogDaemon.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dataLogDaemon.rc \
    vendor/realme/RE58C2/proprietary/system_ext/etc/camera/default_cnr3_param.txt:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/default_cnr3_param.txt \
    vendor/realme/RE58C2/proprietary/system_ext/etc/camera/default_ynr_param.txt:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/default_ynr_param.txt \
    vendor/realme/RE58C2/proprietary/system_ext/etc/init/data_rps.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/data_rps.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/unisoc.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/unisoc.rild.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.security.keymint@2.0-unisoc.service.trusty.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint@2.0-unisoc.service.trusty.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.sensors-service-multihal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors-service-multihal.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.usb-service.example.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb-service.example.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.wifi.supplicant-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi.supplicant-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.wifi@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/odm/etc/init/init.jiiov.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.jiiov.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/ai_engine-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ai_engine-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/autotest.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/autotest.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/boringssl_self_test.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/boringssl_self_test.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/charge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/charge.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/charged.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/charged.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/connmgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/connmgr.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/cp_diskserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cp_diskserver.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/cplog_svc-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cplog_svc-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/dcxsrv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dcxsrv.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/engpc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/engpc.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/enhance-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/enhance-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/face-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/face-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/hdcp-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hdcp-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/hostapd.android.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hostapd.android.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/init.guid.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.guid.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/init.md.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.md.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/init.ums9230_hulk_Natv.nfc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.ums9230_hulk_Natv.nfc.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/lights.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lights.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/memtrack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/memtrack.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/modem_control.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/modem_control.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/network-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/network-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/phasecheckserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/phasecheckserver.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/power.stats-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/power.stats-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/rebootescrow-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rebootescrow-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/refnotify.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/refnotify.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/remosaic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/remosaic.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/rpmbserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rpmbserver.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/slogmodem_vendor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/slogmodem_vendor.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/soter-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/soter-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/srtd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/srtd.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/storageproxyd_android.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/storageproxyd_android.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/systemDebuggerd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/systemDebuggerd.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/tee_rpc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee_rpc.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/thermald.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/thermald.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/trusty-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trusty-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/tsupplicant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tsupplicant.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/tui-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tui-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor-fingerprintmmi-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor-fingerprintmmi-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor-oemlock-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor-oemlock-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor-power-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor-power-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.log-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.log-default.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.oppo.engnative.engineer@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.oppo.engnative.engineer@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.broadcastradio@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.broadcastradio@2.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.commondcs@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.commondcs@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.connmgr@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.connmgr@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.gnss@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.gnss@2.2-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.network@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.network@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.performance@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.performance@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.thermal@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.thermal@2.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.wcn@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.wcn@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor_engineermode.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor_engineermode.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vibrator.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vibrator.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vowifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vowifi.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/wcn.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wcn.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/wcn_chr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wcn_chr.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/yloglite.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/yloglite.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/ueventd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/ueventd.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.boot@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.boot@1.2-service.rc 

    # device/realme/RE58C2/vendor/etc/init/vendor.sprd.hardware.boot@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.boot@1.2-service.rc
    # vendor/realme/RE58C2/proprietary/vendor/etc/init/vndservicemanager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vndservicemanager.rc 




# ===========================
# MISSING VENDOR BINARIES - CORRECT PATHS
# ===========================

# Core vendor binaries
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/bin/charged:$(TARGET_COPY_OUT_VENDOR)/bin/charged \
    vendor/realme/RE58C2/proprietary/vendor/bin/uniber:$(TARGET_COPY_OUT_VENDOR)/bin/uniber \
    vendor/realme/RE58C2/proprietary/vendor/bin/phasecheckserver:$(TARGET_COPY_OUT_VENDOR)/bin/phasecheckserver \
    vendor/realme/RE58C2/proprietary/vendor/bin/refnotify:$(TARGET_COPY_OUT_VENDOR)/bin/refnotify \
    vendor/realme/RE58C2/proprietary/vendor/bin/slogmodem_vendor:$(TARGET_COPY_OUT_VENDOR)/bin/slogmodem_vendor \
    vendor/realme/RE58C2/proprietary/vendor/bin/srtd:$(TARGET_COPY_OUT_VENDOR)/bin/srtd \
    vendor/realme/RE58C2/proprietary/vendor/bin/vndservice:$(TARGET_COPY_OUT_VENDOR)/bin/vndservice 
   # vendor/realme/RE58C2/proprietary/vendor/bin/vndservicemanager:$(TARGET_COPY_OUT_VENDOR)/bin/vndservicemanager




# HAL services
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.gnss@2.2-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.gnss@2.2-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.camera.provider@2.4-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.camera.provider@2.4-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.drm-service.clearkey:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm-service.clearkey \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.gatekeeper@1.0-service.trusty:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper@1.0-service.trusty \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.nfc@1.2-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.nfc@1.2-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.wifi@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.wifi@1.0-service

# Sprd HAL services
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.cplog_svc-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.cplog_svc-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.enhance-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.enhance-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.hdcp-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.hdcp-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.lights-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.lights-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.memtrack-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.memtrack-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.network-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.network-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.oemlock-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.oemlock-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.log-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.log-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.broadcastradio@2.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.broadcastradio@2.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.commondcs@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.commondcs@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.network@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.network@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.performance@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.performance@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.vibrator-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.vibrator-service

# Additional services
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.rebootescrow-service.default:$(TARGET_COPY_OUT_VENDOR)/bin/hw/anCAIdroid.hardware.rebootescrow-service.default \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.oppo.engnative.engineer@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.oppo.engnative.engineer@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.media.c2@1.1-unisoc-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.media.c2@1.1-unisoc-service



PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/vendor/lib,$(TARGET_COPY_OUT_VENDOR)/lib) \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/vendor/lib64,$(TARGET_COPY_OUT_VENDOR)/lib64)\
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/vendor/firmware,$(TARGET_COPY_OUT_VENDOR)/firmware) \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/vendor/framework,$(TARGET_COPY_OUT_VENDOR)/framework)


PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/hw/init.ums9230_hulk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.ums9230_hulk.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/hw/init.ums9230_hulk.usb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.ums9230_hulk.usb.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/hw/init.ram.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.ram.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/hw/init.storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.storage.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/hw/init.cali.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.cali.rc




# Vold stack binaries and libraries
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/system/bin/vold:$(TARGET_COPY_OUT_SYSTEM)/bin/vold \
    vendor/realme/RE58C2/proprietary/system/bin/vold_prepare_subdirs:$(TARGET_COPY_OUT_SYSTEM)/bin/vold_prepare_subdirs \
    vendor/realme/RE58C2/proprietary/system_ext/lib64/libunisocvold.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libunisocvold.so

# Vold init files
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/system/etc/init/vold.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/vold.rc 

# Storage-related binaries
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/bin/sprdstorageproxyd:$(TARGET_COPY_OUT_VENDOR)/bin/sprdstorageproxyd \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/storageproxyd_android.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/storageproxyd_android.rc

# Storage HAL libraries
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/system/lib64/android.hardware.health.storage@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.health.storage@1.0.so \
    vendor/realme/RE58C2/proprietary/system/lib64/android.hardware.health.storage-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/android.hardware.health.storage-V1-ndk.so

# Fstab files (include your device-specific one)
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.RE58C2:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.RE58C2


# Audio
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/a2dp_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/a2dp_audio_policy_configuration.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_effects.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_policy_apm_configuration_configurable.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_apm_configuration_configurable.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_policy_configuration_a2dp_offload_disabled.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration_a2dp_offload_disabled.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_policy_configuration_bluetooth_legacy_hal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration_bluetooth_legacy_hal.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_policy_engine_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_engine_configuration.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_policy_engine_criterion_types.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_engine_criterion_types.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_policy_engine_default_stream_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_engine_default_stream_volumes.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_policy_engine_product_strategies.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_engine_product_strategies.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_policy_engine_stream_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_engine_stream_volumes.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/bluetooth_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_audio_policy_configuration.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/bluetooth_audio_policy_configuration_disable_offload.xml:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_audio_policy_configuration_disable_offload.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/default_volume_tables.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default_volume_tables.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/primary_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/primary_audio_policy_configuration.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/r_submix_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/r_submix_audio_policy_configuration.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/sprd_audio_policy_engine_criteria.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sprd_audio_policy_engine_criteria.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/usb_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usb_audio_policy_configuration.xml

# Camera
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/camera/engineer_camera_config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/engineer_camera_config

# Media Codecs
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/media_codecs_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/media_codecs_google_telephony.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_google_telephony.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/media_codecs_performance_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance_c2.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/media_profiles_turnkey.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_turnkey.xml

# NFC
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf

# Sensors
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf

# WiFi
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/wifi/vendor_hals/unisoc_wifi_hal_arm64.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/vendor_hals/unisoc_wifi_hal_arm64.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf

# Audio Test Files
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/AudioTest_hq/audio_1.mp3:$(TARGET_COPY_OUT_VENDOR)/etc/AudioTest_hq/audio_1.mp3 \
    vendor/realme/RE58C2/proprietary/vendor/etc/AudioTest_hq/receiver.wav:$(TARGET_COPY_OUT_VENDOR)/etc/AudioTest_hq/receiver.wav \
    vendor/realme/RE58C2/proprietary/vendor/etc/AudioTest_hq/spk.wav:$(TARGET_COPY_OUT_VENDOR)/etc/AudioTest_hq/spk.wav

# Dirac Audio
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/dirac/diracmobile.config:$(TARGET_COPY_OUT_VENDOR)/etc/dirac/diracmobile.config \
    vendor/realme/RE58C2/proprietary/vendor/etc/dirac/diracvdd.bin:$(TARGET_COPY_OUT_VENDOR)/etc/dirac/diracvdd.bin \
    vendor/realme/RE58C2/proprietary/vendor/etc/dirac/interfacedb:$(TARGET_COPY_OUT_VENDOR)/etc/dirac/interfacedb

# Engineering PC Configs
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/engpc/chnl/autotest.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/chnl/autotest.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/engpc/chnl/cali.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/chnl/cali.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/engpc/chnl/normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/chnl/normal.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/engpc/chnl/normal_lite.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/chnl/normal_lite.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/engpc/dev/agdsp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/agdsp.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/engpc/dev/ap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/ap.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/engpc/dev/cp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/cp.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/engpc/dev/pc.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/pc.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/engpc/dev/sensorhub.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/sensorhub.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/engpc/dev/wcn.conf:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/dev/wcn.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/engpc/engpc.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/engpc/engpc.cfg

# Display Enhancement
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/3d_lut.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/3d_lut.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/abc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/abc.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/bld.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/bld.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/cms.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/cms.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/dci.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/dci.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/flash.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/flash.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/gamma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/gamma.xml

# LCD Display Profiles
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_ft8057p_ld_mipi_hd_3d_lut.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_ft8057p_ld_mipi_hd_3d_lut.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_ft8057p_ld_mipi_hd_abc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_ft8057p_ld_mipi_hd_abc.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_ft8057p_ld_mipi_hd_bld.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_ft8057p_ld_mipi_hd_bld.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_ft8057p_ld_mipi_hd_cms.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_ft8057p_ld_mipi_hd_cms.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_ft8057p_ld_mipi_hd_gamma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_ft8057p_ld_mipi_hd_gamma.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_boe_mipi_hd_3d_lut.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_boe_mipi_hd_3d_lut.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_boe_mipi_hd_abc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_boe_mipi_hd_abc.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_boe_mipi_hd_bld.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_boe_mipi_hd_bld.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_boe_mipi_hd_cms.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_boe_mipi_hd_cms.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_boe_mipi_hd_gamma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_boe_mipi_hd_gamma.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_lce_mipi_hd_3d_lut.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_lce_mipi_hd_3d_lut.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_lce_mipi_hd_abc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_lce_mipi_hd_abc.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_lce_mipi_hd_bld.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_lce_mipi_hd_bld.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_lce_mipi_hd_cms.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_lce_mipi_hd_cms.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_lce_mipi_hd_gamma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_lce_mipi_hd_gamma.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_lce_new_mipi_hd_3d_lut.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_lce_new_mipi_hd_3d_lut.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_lce_new_mipi_hd_abc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_lce_new_mipi_hd_abc.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_lce_new_mipi_hd_bld.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_lce_new_mipi_hd_bld.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_lce_new_mipi_hd_cms.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_lce_new_mipi_hd_cms.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_hx83108a_lce_new_mipi_hd_gamma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_hx83108a_lce_new_mipi_hd_gamma.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_hjc_cd_mipi_hd_3d_lut.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_hjc_cd_mipi_hd_3d_lut.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_hjc_cd_mipi_hd_abc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_hjc_cd_mipi_hd_abc.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_hjc_cd_mipi_hd_bld.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_hjc_cd_mipi_hd_bld.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_hjc_cd_mipi_hd_cms.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_hjc_cd_mipi_hd_cms.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_hjc_cd_mipi_hd_gamma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_hjc_cd_mipi_hd_gamma.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_inx_mipi_hd_3d_lut.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_inx_mipi_hd_3d_lut.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_inx_mipi_hd_abc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_inx_mipi_hd_abc.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_inx_mipi_hd_bld.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_inx_mipi_hd_bld.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_inx_mipi_hd_cms.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_inx_mipi_hd_cms.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_inx_mipi_hd_gamma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_inx_mipi_hd_gamma.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_ld_hjc_mipi_hd_3d_lut.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_ld_hjc_mipi_hd_3d_lut.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_ld_hjc_mipi_hd_abc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_ld_hjc_mipi_hd_abc.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_ld_hjc_mipi_hd_bld.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_ld_hjc_mipi_hd_bld.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_ld_hjc_mipi_hd_cms.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_ld_hjc_mipi_hd_cms.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_icnl9916c_ld_hjc_mipi_hd_gamma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_icnl9916c_ld_hjc_mipi_hd_gamma.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_td4160_cw_new_mipi_hd_3d_lut.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_td4160_cw_new_mipi_hd_3d_lut.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_td4160_cw_new_mipi_hd_abc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_td4160_cw_new_mipi_hd_abc.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_td4160_cw_new_mipi_hd_bld.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_td4160_cw_new_mipi_hd_bld.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_td4160_cw_new_mipi_hd_cms.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_td4160_cw_new_mipi_hd_cms.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_td4160_cw_new_mipi_hd_gamma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_td4160_cw_new_mipi_hd_gamma.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_td4160_cw_old_mipi_hd_3d_lut.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_td4160_cw_old_mipi_hd_3d_lut.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_td4160_cw_old_mipi_hd_abc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_td4160_cw_old_mipi_hd_abc.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_td4160_cw_old_mipi_hd_bld.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_td4160_cw_old_mipi_hd_bld.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_td4160_cw_old_mipi_hd_cms.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_td4160_cw_old_mipi_hd_cms.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/enhance/lcd_td4160_cw_old_mipi_hd_gamma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/enhance/lcd_td4160_cw_old_mipi_hd_gamma.xml

# Graphics
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/gralloc/gralloc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gralloc/gralloc.xml

# ICAP
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/icap/control/scenes/Type_ISS.xml:$(TARGET_COPY_OUT_VENDOR)/etc/icap/control/scenes/Type_ISS.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/icap/control/IcapSwitchs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/icap/control/IcapSwitchs.xml

# AI Models
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/models/noahark/gesture/tsn_gesture:$(TARGET_COPY_OUT_VENDOR)/etc/models/noahark/gesture/tsn_gesture \
    vendor/realme/RE58C2/proprietary/vendor/etc/models/noahark/imageClassify/README.md:$(TARGET_COPY_OUT_VENDOR)/etc/models/noahark/imageClassify/README.md \
    vendor/realme/RE58C2/proprietary/vendor/etc/models/noahark/imageClassify/cv_imageClassify:$(TARGET_COPY_OUT_VENDOR)/etc/models/noahark/imageClassify/cv_imageClassify \
    vendor/realme/RE58C2/proprietary/vendor/etc/models/noahark/imageClassify/imageclassify_labels.txt:$(TARGET_COPY_OUT_VENDOR)/etc/models/noahark/imageClassify/imageclassify_labels.txt

# Operator Configs
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/operator_config/au_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/operator_config/au_config.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/operator_config/in_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/operator_config/in_config.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/operator_config/jp_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/operator_config/jp_config.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/operator_config/pl_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/operator_config/pl_config.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/operator_config/tw_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/operator_config/tw_config.xml

# Parameter Framework
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/parameter-framework/Settings/Policy/PolicyConfigurableDomains.xml:$(TARGET_COPY_OUT_VENDOR)/etc/parameter-framework/Settings/Policy/PolicyConfigurableDomains.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/parameter-framework/Structure/Policy/ProductStrategies.xml:$(TARGET_COPY_OUT_VENDOR)/etc/parameter-framework/Structure/Policy/ProductStrategies.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/parameter-framework/Structure/Policy/audio_PolicyClass.xml:$(TARGET_COPY_OUT_VENDOR)/etc/parameter-framework/Structure/Policy/audio_PolicyClass.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/parameter-framework/Structure/Policy/audio_PolicySubsystem-CommonTypes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/parameter-framework/Structure/Policy/audio_PolicySubsystem-CommonTypes.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/parameter-framework/Structure/Policy/audio_PolicySubsystem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/parameter-framework/Structure/Policy/audio_PolicySubsystem.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/parameter-framework/ParameterFrameworkConfigurationPolicy.xml:$(TARGET_COPY_OUT_VENDOR)/etc/parameter-framework/ParameterFrameworkConfigurationPolicy.xml

# Camera MFNR
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/raw_mfnr/raw_mfnr/const_file.txt:$(TARGET_COPY_OUT_VENDOR)/etc/raw_mfnr/raw_mfnr/const_file.txt \
    vendor/realme/RE58C2/proprietary/vendor/etc/raw_mfnr/raw_mfnr/raw_mfnr_tuning.txt:$(TARGET_COPY_OUT_VENDOR)/etc/raw_mfnr/raw_mfnr/raw_mfnr_tuning.txt

# Boot/Charging Images
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/res/images/colon_1080X1920.png:$(TARGET_COPY_OUT_VENDOR)/etc/res/images/colon_1080X1920.png \
    vendor/realme/RE58C2/proprietary/vendor/etc/res/images/colon_1440X2560.png:$(TARGET_COPY_OUT_VENDOR)/etc/res/images/colon_1440X2560.png \
    vendor/realme/RE58C2/proprietary/vendor/etc/res/images/colon_360X640.png:$(TARGET_COPY_OUT_VENDOR)/etc/res/images/colon_360X640.png \
    vendor/realme/RE58C2/proprietary/vendor/etc/res/images/colon_480X800.png:$(TARGET_COPY_OUT_VENDOR)/etc/res/images/colon_480X800.png \
    vendor/realme/RE58C2/proprietary/vendor/etc/res/images/colon_720X1280.png:$(TARGET_COPY_OUT_VENDOR)/etc/res/images/colon_720X1280.png

# Seccomp Policies
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.1-unisoc-seccomp_policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.1-unisoc-seccomp_policy \
    vendor/realme/RE58C2/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy

# Touch Input
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/sinput/NVTCapacitiveTouchScreen.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sinput/NVTCapacitiveTouchScreen.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/sinput/adaptive_ts.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sinput/adaptive_ts.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/sinput/fts_ts.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sinput/fts_ts.conf

# System Configuration Files
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/BBAT.conf:$(TARGET_COPY_OUT_VENDOR)/etc/BBAT.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/FD_tunning_param.xml:$(TARGET_COPY_OUT_VENDOR)/etc/FD_tunning_param.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/analyzer.py:$(TARGET_COPY_OUT_VENDOR)/etc/analyzer.py \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_config.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/blackAppList.xml:$(TARGET_COPY_OUT_VENDOR)/etc/blackAppList.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/config.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/cp_dump_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cp_dump_info.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/deviceidle.xml:$(TARGET_COPY_OUT_VENDOR)/etc/deviceidle.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/dynamic_debug_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dynamic_debug_config.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.RMX3624:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.RMX3624 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.cali:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.cali \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.charge_mode:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.charge_mode \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.enableswap:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.enableswap \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.module:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.module \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_1h10:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_1h10 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_1h10_go:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_1h10_go \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_4h10:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_4h10 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_4h10_go:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_4h10_go \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_6h10:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_6h10 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_7h10:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_7h10 \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_haps:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_haps \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_hulk:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_hulk \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_nico:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_nico \
    vendor/realme/RE58C2/proprietary/vendor/etc/fstab.ums9230_zebu:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.ums9230_zebu \
    vendor/realme/RE58C2/proprietary/vendor/etc/imsUserAgent.xml:$(TARGET_COPY_OUT_VENDOR)/etc/imsUserAgent.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/lmkd_param.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lmkd_param.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/log_settings.xml:$(TARGET_COPY_OUT_VENDOR)/etc/log_settings.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/log_settings_autotest.xml:$(TARGET_COPY_OUT_VENDOR)/etc/log_settings_autotest.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/log_settings_cali.xml:$(TARGET_COPY_OUT_VENDOR)/etc/log_settings_cali.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/log_settings_factory.xml:$(TARGET_COPY_OUT_VENDOR)/etc/log_settings_factory.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/log_settings_lite.xml:$(TARGET_COPY_OUT_VENDOR)/etc/log_settings_lite.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/mkshrc:$(TARGET_COPY_OUT_VENDOR)/etc/mkshrc \
    vendor/realme/RE58C2/proprietary/vendor/etc/modem_cp_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/modem_cp_info.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/modem_sp_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/modem_sp_info.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/numeric_operator.xml:$(TARGET_COPY_OUT_VENDOR)/etc/numeric_operator.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/nvmerge.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/nvmerge.cfg \
    vendor/realme/RE58C2/proprietary/vendor/etc/power_info.db:$(TARGET_COPY_OUT_VENDOR)/etc/power_info.db \
    vendor/realme/RE58C2/proprietary/vendor/etc/power_resource_file_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_resource_file_info.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/power_resource_id_define.txt:$(TARGET_COPY_OUT_VENDOR)/etc/power_resource_id_define.txt \
    vendor/realme/RE58C2/proprietary/vendor/etc/power_scene_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_scene_config.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/power_scene_id_define.txt:$(TARGET_COPY_OUT_VENDOR)/etc/power_scene_id_define.txt \
    vendor/realme/RE58C2/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/realme/RE58C2/proprietary/vendor/etc/pwctl_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/pwctl_config.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/scenario.conf:$(TARGET_COPY_OUT_VENDOR)/etc/scenario.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/sixth_param.txt:$(TARGET_COPY_OUT_VENDOR)/etc/sixth_param.txt \
    vendor/realme/RE58C2/proprietary/vendor/etc/sixth_param_voip.txt:$(TARGET_COPY_OUT_VENDOR)/etc/sixth_param_voip.txt \
    vendor/realme/RE58C2/proprietary/vendor/etc/slog_modem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/slog_modem_autotest.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem_autotest.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/slog_modem_cali.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem_cali.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/slog_modem_factory.conf:$(TARGET_COPY_OUT_VENDOR)/etc/slog_modem_factory.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/spirentroot.cer:$(TARGET_COPY_OUT_VENDOR)/etc/spirentroot.cer \
    vendor/realme/RE58C2/proprietary/vendor/etc/sprd_hdr_tuning.param:$(TARGET_COPY_OUT_VENDOR)/etc/sprd_hdr_tuning.param \
    vendor/realme/RE58C2/proprietary/vendor/etc/supl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/supl.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/task_profiles.json:$(TARGET_COPY_OUT_VENDOR)/etc/task_profiles.json \
    vendor/realme/RE58C2/proprietary/vendor/etc/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/ueventd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/ueventd.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/uniber.conf:$(TARGET_COPY_OUT_VENDOR)/etc/uniber.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/wcn_chr.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wcn_chr.ini \
    vendor/realme/RE58C2/proprietary/vendor/etc/wifisar.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wifisar.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/ylog.conf.custom:$(TARGET_COPY_OUT_VENDOR)/etc/ylog.conf.custom \
    vendor/realme/RE58C2/proprietary/vendor/etc/ylog.conf.debug:$(TARGET_COPY_OUT_VENDOR)/etc/ylog.conf.debug \
    vendor/realme/RE58C2/proprietary/vendor/etc/ylog.conf.factorytest:$(TARGET_COPY_OUT_VENDOR)/etc/ylog.conf.factorytest \
    vendor/realme/RE58C2/proprietary/vendor/etc/ylog.conf.user:$(TARGET_COPY_OUT_VENDOR)/etc/ylog.conf.user \
    vendor/realme/RE58C2/proprietary/vendor/etc/yloglite.conf:$(TARGET_COPY_OUT_VENDOR)/etc/yloglite.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/yloglitesource.conf:$(TARGET_COPY_OUT_VENDOR)/etc/yloglitesource.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/ylogsource.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ylogsource.conf

#FAKED PACKAGES
#PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.boot@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.boot@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.boot@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.boot@1.0-service



# Essential System Components
# ========================
PRODUCT_PACKAGES += \
    charger \
    charger_res_images \
    watchdogd


