#!/bin/bash

# Create dupes directory
mkdir -p dupes

# List of files to move (preserving path)
files=(
vendor/lib/android.frameworks.cameraservice.common@2.0.so
vendor/lib/android.frameworks.cameraservice.device@2.0.so
vendor/lib/android.frameworks.cameraservice.device@2.1.so
vendor/lib/android.frameworks.cameraservice.service@2.0.so
vendor/lib/android.frameworks.cameraservice.service@2.1.so
vendor/lib/android.frameworks.cameraservice.service@2.2.so
vendor/lib/android.frameworks.sensorservice@1.0.so
vendor/lib/android.hardware.audio.common-util.so
vendor/lib/android.hardware.audio.common@5.0.so
vendor/lib/android.hardware.audio.common@7.0-enums.so
vendor/lib/android.hardware.audio.common@7.0-util.so
vendor/lib/android.hardware.audio.common@7.0.so
vendor/lib/android.hardware.audio.common@7.1-enums.so
vendor/lib/android.hardware.audio.common@7.1-util.so
vendor/lib/android.hardware.audio.effect@7.0-util.so
vendor/lib/android.hardware.audio.effect@7.0.so
vendor/lib/android.hardware.audio@7.0-util.so
vendor/lib/android.hardware.audio@7.0.so
vendor/lib/android.hardware.audio@7.1-util.so
vendor/lib/android.hardware.audio@7.1.so
vendor/lib/android.hardware.bluetooth.audio-impl.so
vendor/lib/android.hardware.bluetooth.audio@2.0.so
vendor/lib/android.hardware.bluetooth.audio@2.1.so
vendor/lib/android.hardware.boot@1.0.so
vendor/lib/android.hardware.boot@1.1.so
vendor/lib/android.hardware.boot@1.2.so
vendor/lib/android.hardware.broadcastradio@1.0.so
vendor/lib/android.hardware.camera.common@1.0.so
vendor/lib/android.hardware.camera.device@1.0.so
vendor/lib/android.hardware.camera.device@3.2.so
vendor/lib/android.hardware.camera.device@3.3.so
vendor/lib/android.hardware.camera.device@3.4.so
vendor/lib/android.hardware.camera.device@3.5.so
vendor/lib/android.hardware.camera.device@3.6.so
vendor/lib/android.hardware.camera.provider@2.4.so
vendor/lib/android.hardware.cas.native@1.0.so
vendor/lib/android.hardware.cas@1.0.so
vendor/lib/android.hardware.cas@1.1.so
vendor/lib/android.hardware.cas@1.2.so
vendor/lib/android.hardware.gnss.measurement_corrections@1.0.so
vendor/lib/android.hardware.gnss.measurement_corrections@1.1.so
vendor/lib/android.hardware.gnss.visibility_control@1.0.so
vendor/lib/android.hardware.gnss@1.0.so
vendor/lib/android.hardware.gnss@1.1.so
vendor/lib/android.hardware.gnss@2.0.so
vendor/lib/android.hardware.gnss@2.1.so
vendor/lib/android.hardware.media.c2@1.0.so
vendor/lib/android.hardware.media.c2@1.1.so
vendor/lib/android.hardware.nfc@1.0.so
vendor/lib/android.hardware.radio.deprecated@1.0.so
vendor/lib/android.hardware.radio@1.0.so
vendor/lib/android.hardware.radio@1.1.so
vendor/lib/android.hardware.radio@1.2.so
vendor/lib/android.hardware.secure_element@1.0.so
vendor/lib/android.hardware.sensors@1.0.so
vendor/lib/android.hardware.sensors@2.0-ScopedWakelock.so
vendor/lib/android.hardware.sensors@2.0.so
vendor/lib/android.hardware.sensors@2.1.so
vendor/lib/android.hardware.thermal@1.0.so
vendor/lib/android.hardware.thermal@2.0.so
vendor/lib/android.hidl.allocator@1.0.so
vendor/lib/android.media.audio.common.types-V1-cpp.so
vendor/lib/audioclient-types-aidl-cpp.so
vendor/lib/av-types-aidl-cpp.so
vendor/lib/camera.device@1.0-impl.so
vendor/lib/framework-permission-aidl-cpp.so
vendor/lib/hw/android.hardware.audio.effect@7.0-impl.so
vendor/lib/hw/android.hardware.audio@7.1-impl.so
vendor/lib/hw/android.hardware.boot@1.0-impl-1.2.so
vendor/lib/hw/android.hardware.broadcastradio@1.0-impl.so
vendor/lib/hw/android.hardware.nfc@1.0-impl.so
vendor/lib/hw/android.hardware.renderscript@1.0-impl.so
vendor/lib/hw/audio.bluetooth.default.so
vendor/lib/hw/audio.primary.default.so
vendor/lib/hw/audio.r_submix.default.so
vendor/lib/hw/audio.usb.default.so
vendor/lib/hw/bootctrl.default.so
vendor/lib/hw/gralloc.default.so
vendor/lib/hw/local_time.default.so
vendor/lib/hw/power.default.so
vendor/lib/hw/thermal.default.so
vendor/lib/hw/vibrator.default.so
vendor/lib/libalsautils.so
vendor/lib/libaudioclient_aidl_conversion.so
vendor/lib/libaudiofoundation.so
vendor/lib/libavservices_minijail.so
vendor/lib/libbluetooth_audio_session.so
vendor/lib/libbluetooth_audio_session_aidl.so
vendor/lib/libcamera2ndk_vendor.so
vendor/lib/libcodec2_hidl@1.0.so
vendor/lib/libcodec2_hidl@1.1.so
vendor/lib/libcodec2_hidl_plugin.so
vendor/lib/libcodec2_vndk.so
vendor/lib/libdrm.so
vendor/lib/libeffects.so
vendor/lib/libeffectsconfig.so
vendor/lib/libhwbinder.so
vendor/lib/libhwc2on1adapter.so
vendor/lib/libmediautils_vendor.so
vendor/lib/libmemunreachable.so
vendor/lib/libnbaio_mono.so
vendor/lib/libopus.so
vendor/lib/libprotobuf-cpp-full-3.9.1.so
vendor/lib/libprotobuf-cpp-lite-3.9.1.so
vendor/lib/librilutils.so
vendor/lib/libsensorndkbridge.so
vendor/lib/libsfplugin_ccodec_utils.so
vendor/lib/libshmemcompat.so
vendor/lib/libshmemutil.so
vendor/lib/libstagefright_amrnb_common.so
vendor/lib/libstagefright_bufferpool@2.0.1.so
vendor/lib/libstagefright_enc_common.so
vendor/lib/libstagefright_flacdec.so
vendor/lib/libstagefright_soft_aacdec.so
vendor/lib/libstagefright_soft_aacenc.so
vendor/lib/libstagefright_soft_amrdec.so
vendor/lib/libstagefright_soft_amrnbenc.so
vendor/lib/libstagefright_soft_amrwbenc.so
vendor/lib/libstagefright_soft_avcdec.so
vendor/lib/libstagefright_soft_avcenc.so
vendor/lib/libstagefright_soft_flacdec.so
vendor/lib/libstagefright_soft_flacenc.so
vendor/lib/libstagefright_soft_g711dec.so
vendor/lib/libstagefright_soft_gsmdec.so
vendor/lib/libstagefright_soft_hevcdec.so
vendor/lib/libstagefright_soft_mp3dec.so
vendor/lib/libstagefright_soft_mpeg2dec.so
vendor/lib/libstagefright_soft_mpeg4dec.so
vendor/lib/libstagefright_soft_mpeg4enc.so
vendor/lib/libstagefright_soft_opusdec.so
vendor/lib/libstagefright_soft_rawdec.so
vendor/lib/libstagefright_soft_vorbisdec.so
vendor/lib/libstagefright_soft_vpxdec.so
vendor/lib/libstagefright_soft_vpxenc.so
vendor/lib/libstagefright_softomx.so
vendor/lib/libstagefright_softomx_plugin.so
vendor/lib/libtinycompress.so
vendor/lib/libtinyxml.so
vendor/lib/libtrusty.so
vendor/lib/libvibrator.so
vendor/lib/libvorbisidec.so
vendor/lib/libvpx.so
vendor/lib/libwifi-hal.so
vendor/lib/mediacas/libclearkeycasplugin.so
vendor/lib/mediadrm/libdrmclearkeyplugin.so
vendor/lib/shared-file-region-aidl-cpp.so
vendor/lib/soundfx/libaudiopreprocessing.so
vendor/lib/soundfx/libbundlewrapper.so
vendor/lib/soundfx/libdownmix.so
vendor/lib/soundfx/libdynproc.so
vendor/lib/soundfx/libeffectproxy.so
vendor/lib/soundfx/libhapticgenerator.so
vendor/lib/soundfx/libldnhncr.so
vendor/lib/soundfx/libreverbwrapper.so
vendor/lib/soundfx/libvisualizer.so
vendor/lib64/android.frameworks.cameraservice.common@2.0.so
vendor/lib64/android.frameworks.cameraservice.device@2.0.so
vendor/lib64/android.frameworks.cameraservice.device@2.1.so
vendor/lib64/android.frameworks.cameraservice.service@2.0.so
vendor/lib64/android.frameworks.cameraservice.service@2.1.so
vendor/lib64/android.frameworks.cameraservice.service@2.2.so
vendor/lib64/android.frameworks.sensorservice@1.0.so
vendor/lib64/android.hardware.audio.common-util.so
vendor/lib64/android.hardware.audio.common@5.0.so
vendor/lib64/android.hardware.audio.common@7.0-enums.so
vendor/lib64/android.hardware.audio.common@7.0-util.so
vendor/lib64/android.hardware.audio.common@7.0.so
vendor/lib64/android.hardware.audio.common@7.1-enums.so
vendor/lib64/android.hardware.audio.common@7.1-util.so
vendor/lib64/android.hardware.audio.effect@7.0-util.so
vendor/lib64/android.hardware.audio.effect@7.0.so
vendor/lib64/android.hardware.audio@7.0-util.so
vendor/lib64/android.hardware.audio@7.0.so
vendor/lib64/android.hardware.audio@7.1-util.so
vendor/lib64/android.hardware.audio@7.1.so
vendor/lib64/android.hardware.biometrics.common-V2-ndk.so
vendor/lib64/android.hardware.biometrics.face-V2-ndk.so
vendor/lib64/android.hardware.biometrics.fingerprint@2.1.so
vendor/lib64/android.hardware.bluetooth.audio-impl.so
vendor/lib64/android.hardware.bluetooth.audio@2.0.so
vendor/lib64/android.hardware.bluetooth.audio@2.1.so
vendor/lib64/android.hardware.bluetooth@1.0.so
vendor/lib64/android.hardware.bluetooth@1.1.so
vendor/lib64/android.hardware.boot@1.0.so
vendor/lib64/android.hardware.boot@1.1.so
vendor/lib64/android.hardware.boot@1.2.so
vendor/lib64/android.hardware.broadcastradio@1.0.so
vendor/lib64/android.hardware.broadcastradio@2.0.so
vendor/lib64/android.hardware.camera.common@1.0.so
vendor/lib64/android.hardware.camera.device@1.0.so
vendor/lib64/android.hardware.camera.device@3.2.so
vendor/lib64/android.hardware.camera.device@3.3.so
vendor/lib64/android.hardware.camera.device@3.4.so
vendor/lib64/android.hardware.camera.device@3.5.so
vendor/lib64/android.hardware.camera.device@3.6.so
vendor/lib64/android.hardware.camera.provider@2.4.so
vendor/lib64/android.hardware.cas.native@1.0.so
vendor/lib64/android.hardware.cas@1.0.so
vendor/lib64/android.hardware.gatekeeper@1.0.so
vendor/lib64/android.hardware.gnss.measurement_corrections@1.0.so
vendor/lib64/android.hardware.gnss.measurement_corrections@1.1.so
vendor/lib64/android.hardware.gnss.visibility_control@1.0.so
vendor/lib64/android.hardware.gn
etc/libnfc-nci.conf
etc/seccomp_policy/mediacodec.policy
lib/libstagefright_bufferpool@2.0.1.so
lib/libstagefright_codecbase.so
lib/libstagefright_framecapture_utils.so
lib/libstagefright_surface_utils.so
lib/libstagefright_wfd.so
lib64/libstagefright_bufferpool@2.0.1.so
lib64/libstagefright_codecbase.so
lib64/libstagefright_framecapture_utils.so
lib64/libstagefright_surface_utils.so
lib64/libstagefright_wfd.so
vendor/bin/hw/android.hardware.audio.service
vendor/bin/hw/android.hardware.biometrics.fingerprint@2.1-service
vendor/bin/hw/android.hardware.camera.provider@2.4-service
vendor/bin/hw/android.hardware.cas@1.2-service
vendor/bin/hw/android.hardware.drm-service.clearkey
vendor/bin/hw/android.hardware.gatekeeper@1.0-service.trusty
vendor/bin/hw/android.hardware.graphics.composer@2.4-service
vendor/bin/hw/android.hardware.health-service.example
vendor/bin/hw/android.hardware.media.omx@1.0-service
vendor/bin/hw/android.hardware.nfc@1.2-service
vendor/bin/hw/android.hardware.power.stats-service.example
vendor/bin/hw/android.hardware.rebootescrow-service.default
vendor/bin/hw/android.hardware.sensors-service.multihal
vendor/bin/hw/android.hardware.usb-service.example
vendor/bin/hw/android.hardware.wifi@1.0-service
vendor/bin/hw/vendor.oppo.engnative.engineer@1.0-service
)

# Copy each file into dupes/ preserving directory structure
for f in "${files[@]}"; do
    # Check if file exists before trying to move it
    if [ -e "$f" ]; then
        mkdir -p "dupes/$(dirname "$f")"
        mv -- "$f" "dupes/$f"
    else
        echo "Warning: File '$f' does not exist, skipping."
    fi
done